// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2f6JxZMyoKXIx3WgbaWhmsASXDhF2Ap8',
    appId: '1:513160896775:web:9a8fa78abf8172d051a5a2',
    messagingSenderId: '513160896775',
    projectId: 'cyberlog-8fac4',
    authDomain: 'cyberlog-8fac4.firebaseapp.com',
    storageBucket: 'cyberlog-8fac4.firebasestorage.app',
    measurementId: 'G-395T60KFTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpf2eUcMXd7e2-uxl15xuv7m8qdhAMsjY',
    appId: '1:513160896775:android:b03c2844b97af74651a5a2',
    messagingSenderId: '513160896775',
    projectId: 'cyberlog-8fac4',
    storageBucket: 'cyberlog-8fac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfBtWYQTFCJNsYIVMK3U0LmR8L4y7GK0',
    appId: '1:513160896775:ios:cffdfe709e93a71351a5a2',
    messagingSenderId: '513160896775',
    projectId: 'cyberlog-8fac4',
    storageBucket: 'cyberlog-8fac4.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfBtWYQTFCJNsYIVMK3U0LmR8L4y7GK0',
    appId: '1:513160896775:ios:cffdfe709e93a71351a5a2',
    messagingSenderId: '513160896775',
    projectId: 'cyberlog-8fac4',
    storageBucket: 'cyberlog-8fac4.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2f6JxZMyoKXIx3WgbaWhmsASXDhF2Ap8',
    appId: '1:513160896775:web:9e0f52951f2a3ade51a5a2',
    messagingSenderId: '513160896775',
    projectId: 'cyberlog-8fac4',
    authDomain: 'cyberlog-8fac4.firebaseapp.com',
    storageBucket: 'cyberlog-8fac4.firebasestorage.app',
    measurementId: 'G-P350WQ4YGV',
  );
}
